### ISSUE TITLE
Need help with an error.

### ISSUE THREAD

**Issue by Plaguenide** [Reese245/Amiami-Bot#1]
`Current google-chrome version is 101.0.4951
Get LATEST chromedriver version for 101.0.4951 google-chrome
Driver [C:\Users\1\.wdm\drivers\chromedriver\win32\101.0.4951.41\chromedriver.exe] found in cache
Item in stock.
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text\Works\#AmiAmi Scrapper", line 37, in <module>
    addToCartBtn.click()
  File "C:\Python 3.10.4\lib\site-packages\selenium\webdriver\remote\webelement.py", line 81, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Python 3.10.4\lib\site-packages\selenium\webdriver\remote\webelement.py", line 740, in _execute
    return self._parent.execute(command, params)
  File "C:\Python 3.10.4\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "C:\Python 3.10.4\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=101.0.4951.54)
Stacktrace:
Backtrace:
	Ordinal0 [0x0028B8F3+2406643]
	Ordinal0 [0x0021AF31+1945393]
	Ordinal0 [0x0010C610+837136]
	Ordinal0 [0x0013A2D3+1024723]
	Ordinal0 [0x00130083+983171]
	Ordinal0 [0x0015427C+1131132]
	Ordinal0 [0x0012FA64+981604]
	Ordinal0 [0x00154494+1131668]
	Ordinal0 [0x00164682+1197698]
	Ordinal0 [0x00154096+1130646]
	Ordinal0 [0x0012E636+976438]
	Ordinal0 [0x0012F546+980294]
	GetHandleVerifier [0x004F9612+2498066]
	GetHandleVerifier [0x004EC920+2445600]
	GetHandleVerifier [0x00324F2A+579370]
	GetHandleVerifier [0x00323D36+574774]
	Ordinal0 [0x00221C0B+1973259]
	Ordinal0 [0x00226688+1992328]
	Ordinal0 [0x00226775+1992565]
	Ordinal0 [0x0022F8D1+2029777]
	BaseThreadInitThunk [0x7758FA29+25]
	RtlGetAppContainerNamedObjectPath [0x77927A7E+286]
	RtlGetAppContainerNamedObjectPath [0x77927A4E+238]
	(No symbol) [0x00000000]

[Finished in 15.4s]

This is all the code, I was checking if it could work but I still have no idea because pre ordering is not yet available and I want to see if the refresh will work. Sorry for any inconveniences this is my first time using python and this kind of bot.

**Comment by Plaguenide** [comment]
Never mind, it does work, just not when pre ordering has not started, I thought it would keep refreshing until it became in stock. Could it be possible to make one work like that?
